INSERT INTO COMPANIES(COMPANY_ID, NAME) VALUES (default, 'Extia');

INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Vegan');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Gluten free');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Hallal');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Kasher');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Viande');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Poisson');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Sans sucre');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Fruit');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Légumes');