INSERT INTO COMPANIES(COMPANY_ID, NAME) VALUES (default, 'Extia');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Vegan');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Gluten free');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Hallal');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Kasher');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Viande');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Poisson');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Sans sucre');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Fruit');
INSERT INTO CATEGORIES(CATEGORY_ID, NAME) VALUES (default, 'Légumes');

INSERT INTO ACCOUNTS(ACCOUNT_ID, ID_NFC, LOGO, EMAIL, PASSWORD, SCORE, COMPANY_ID) VALUES (default, 'Légumes','légumes','lgumes@leg.um','dsqdqs', 10, 1);

INSERT INTO CONTAINERS(CONTAINER_ID, SIZE, COMPANY_ID) VALUES (default, 100, 1);

INSERT INTO PRODUCTS(PRODUCT_ID, NAME, DESCRIPTION) VALUES (default, 'Fraises', 'Mara des bois');
INSERT INTO PRODUCTS(PRODUCT_ID, NAME, DESCRIPTION) VALUES (default, 'Framboises', 'Oui');

